---
- name: Using ServiceNow Collection
  hosts: localhost
  gather_facts: no

  tasks:
  - name: Create an incident
    servicenow.servicenow.snow_record:
      username: admin
      password: llDpE4MZ6thQ
      instance: dev76820
      state: present
      data:
        category: "software"
        subcategory: "os"
        short_description: "Automation Services Catalog - Ansible Automation Order"
        state: 2
        description: "Order ID : {{orderid}}\r\n {{productname}} was ordered by {{username}}<{{useremail}}>\r\n Date : {{orderedat}}\r\n  Order Parameters\r\n   ----------------\r\n     CPU's = {{cpu}}\r\n    Memory =  {{memory}}\r\n    Platform = {{productplatform}}"
        severity: 3
        priority: 2
    register: new_incident
  - debug: msg="Record Number {{new_incident['record']['number']}}"
  - set_stats:
      data:
        expose_to_cloud_redhat_com_record_number: "{{new_incident['record']['number']}}"

