---
- name: Using ServiceNow Collection
  hosts: localhost
  gather_facts: no

  tasks:
  - name: Create an incident
    servicenow.servicenow.snow_record:
      username: admin
      password: llDpE4MZ6thQ
      instance: dev76820
      state: present
      data:
        category: "software"
        subcategory: "os"
        short_description: "Automation Services Catalog - Ansible Automation Order"
        state: 2
        description: "Order ID : {{orderid}} --- {{productname}} was ordered by {{username}}<{{useremail}}> on {{orderedat}}. CPU's = {{cpu}} | Memory = {{memory}} on Platform {{productplatform}}"
        severity: 3
        priority: 2
