---
- name: Using ServiceNow Collection
  hosts: localhost
  gather_facts: no

  tasks:
  - name: Close an incident
    servicenow.servicenow.snow_record:
      username: admin
      password: llDpE4MZ6thQ
      instance: dev76820
      state: present
      number: "{{ record_number }}"
      data:
        state: 7
        close_notes: "Done Done"
        incident_state: "7"
        close_code: "Solved (Permanently)"
    register: new_incident
